### ISSUE TITLE
Implement Unit Testing for React Components

### ISSUE THREAD

**Issue by movarnell** [infinitepixel-dev/helpcodeit-Vite#383]
We need to set up unit testing for our Vite Tailwind CSS React website to ensure that all pages and links are functioning correctly. The goal is to use React Testing Library along with Jest to write tests for our React components. This will help catch any issues with navigation, rendering, and basic component functionality before they go live.

### **Tasks:**

1. **Install Testing Libraries:**
   - Install Jest and React Testing Library as development dependencies.
     ```bash
     npm install --save-dev jest @testing-library/react @testing-library/jest-dom
     ```

2. **Configure Jest:**
   - Ensure Jest is properly configured in the project. This may include adding a `jest.config.js` file if necessary.
   - Verify that the `package.json` has the following script to run tests:
     ```json
     "scripts": {
       "test": "jest"
     }
     ```

3. **Create Basic Test Files:**
   - Create a test file for each key component (e.g., `App.test.js`).
   - Write a basic test to verify that the main page and key navigation links render correctly.
     Example test:
     ```javascript
     import { render, screen } from '@testing-library/react';
     import App from './App';

     test('renders homepage link', () => {
       render(<App />);
       const homeLink = screen.getByText(/Home/i);
       expect(homeLink).toBeInTheDocument();
     });
     ```

4. **Run Tests:**
   - Run the tests locally to ensure that they pass:
     ```bash
     npm test
     ```

5. **Document Testing Procedures:**
   - Update the project’s README or create a new `TESTING.md` file that outlines how to run tests and what to consider when adding new tests.
   - Include instructions for running tests in CI/CD if applicable.

6. **Continuous Integration (Optional):**
   - Set up Continuous Integration (CI) to automatically run tests on push/pull requests (e.g., using GitHub Actions).

---

### **Acceptance Criteria:**

- [ ] Jest and React Testing Library are installed and configured.
- [ ] Basic test files are created for key components.
- [ ] Tests are successfully run locally.
- [ ] Documentation on running and writing tests is provided.
- [ ] (Optional) CI is configured to run tests on push/pull requests.

---

### **Additional Notes:**

- Focus on testing critical paths first, such as the rendering of the main page and navigation links.
- Consider setting up more comprehensive tests as the project evolves.
